const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Timeline,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.advert,
		C3.Plugins.progressbar,
		C3.Plugins.NinePatch,
		C3.Plugins.Arr,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.video.Acts.SetOpacity,
		C3.Plugins.video.Exps.Opacity,
		C3.Plugins.Text.Acts.SetEffectParam,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Text.Acts.SetResolutionMode,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.progressbar.Acts.SetCSSStyle,
		C3.Plugins.progressbar.Cnds.CompareProgress,
		C3.Plugins.progressbar.Exps.Progress,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText
	];
};
self.C3_JsPropNameTable = [
	{pineatmntree: 0},
	{Background: 0},
	{SceneColliderID: 0},
	{Collider: 0},
	{Interests: 0},
	{Passthroughwall: 0},
	{SceneSort: 0},
	{RedObjects: 0},
	{WallID: 0},
	{Solid: 0},
	{Wall: 0},
	{ExitLevelID: 0},
	{Door: 0},
	{UniqueItemInside: 0},
	{ItemSprite: 0},
	{Scanned: 0},
	{scanCheckpoint: 0},
	{journalid: 0},
	{casettebeingused: 0},
	{colliderbeingused: 0},
	{teleporterbeingused: 0},
	{fakedoorbeingused: 0},
	{Cassette: 0},
	{TPDestID: 0},
	{Teleporter: 0},
	{FakeDoor: 0},
	{lvldestid: 0},
	{levelteleporter: 0},
	{RedScan: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{WhiteScan: 0},
	{item: 0},
	{persistpointcloud: 0},
	{eastereggdot: 0},
	{Pathfinding: 0},
	{ChasingEnemy: 0},
	{patrollingIndex: 0},
	{Patrolingenemy: 0},
	{sprintspeed: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Player: 0},
	{beingused: 0},
	{Interaction_prompt: 0},
	{Pin: 0},
	{INGAME_DIAG: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{AJAX: 0},
	{TimelineController: 0},
	{Audio: 0},
	{cuimg1f: 0},
	{cu: 0},
	{cu2: 0},
	{cu2_: 0},
	{IMGS: 0},
	{PagerAsset: 0},
	{recapBG: 0},
	{Video: 0},
	{MobileAdvert: 0},
	{COMPLETIONNEXTTEXT: 0},
	{COMPLETIONRANK: 0},
	{COMPLETIONRECAP: 0},
	{COMPLETIONSUMMARY: 0},
	{COMPLETIONTITLE: 0},
	{MenuBGVid: 0},
	{effects: 0},
	{MENUTITLE: 0},
	{MenuUIID: 0},
	{sizedisplacement: 0},
	{UIText: 0},
	{ProgressBar: 0},
	{DIATEXT: 0},
	{DIATXTPERSN: 0},
	{Dialougeindex: 0},
	{MaxDialougeIndex: 0},
	{DIALOUGEBG: 0},
	{InitText: 0},
	{KEYTEXT: 0},
	{PagerAsset2: 0},
	{Player_talk: 0},
	{playerdiag: 0},
	{Gameovertext: 0},
	{currentdialouge: 0},
	{maxdialouge: 0},
	{enablemovement: 0},
	{enablescanning: 0},
	{TUTORIALTEXT: 0},
	{tutdialouge: 0},
	{tutorialsection: 0},
	{tutorialbox: 0},
	{CamFollowerMenu: 0},
	{CUTSCENECAM: 0},
	{ItemList: 0},
	{C1: 0},
	{B1: 0},
	{Button: 0},
	{Button2: 0},
	{SceCollider2_ID: 0},
	{Collider2: 0},
	{Video2: 0},
	{playerwalkingsound: 0},
	{nextlevel: 0},
	{rep: 0},
	{bossitemtake: 0},
	{finalitemtake: 0},
	{potentialpay: 0},
	{totalpay: 0},
	{totalmoneygot: 0},
	{bankaccount: 0},
	{RandoDest: 0},
	{DestinationID: 0},
	{InteractionStep: 0},
	{LScanCooldown: 0},
	{Particlecount: 0},
	{totalitemworth: 0},
	{LevelScanCount: 0},
	{TotalScanCheckpoint: 0},
	{CurrentLevel: 0}
];

self.InstanceType = {
	pineatmntree: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Collider: class extends self.ISpriteInstance {},
	Interests: class extends self.ISpriteInstance {},
	Passthroughwall: class extends self.ISpriteInstance {},
	RedObjects: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Door: class extends self.ISpriteInstance {},
	ItemSprite: class extends self.ISpriteInstance {},
	scanCheckpoint: class extends self.ISpriteInstance {},
	Cassette: class extends self.ISpriteInstance {},
	Teleporter: class extends self.ISpriteInstance {},
	FakeDoor: class extends self.ISpriteInstance {},
	levelteleporter: class extends self.ISpriteInstance {},
	RedScan: class extends self.ISpriteInstance {},
	WhiteScan: class extends self.ISpriteInstance {},
	item: class extends self.ISpriteInstance {},
	persistpointcloud: class extends self.ISpriteInstance {},
	eastereggdot: class extends self.ISpriteInstance {},
	ChasingEnemy: class extends self.ISpriteInstance {},
	Patrolingenemy: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Interaction_prompt: class extends self.ITextInstance {},
	INGAME_DIAG: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	cuimg1f: class extends self.ISpriteInstance {},
	cu: class extends self.ISpriteInstance {},
	cu2: class extends self.ISpriteInstance {},
	cu2_: class extends self.ISpriteInstance {},
	IMGS: class extends self.ISpriteInstance {},
	PagerAsset: class extends self.ISpriteInstance {},
	recapBG: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	MobileAdvert: class extends self.IInstance {},
	COMPLETIONNEXTTEXT: class extends self.ITextInstance {},
	COMPLETIONRANK: class extends self.ITextInstance {},
	COMPLETIONRECAP: class extends self.ITextInstance {},
	COMPLETIONSUMMARY: class extends self.ITextInstance {},
	COMPLETIONTITLE: class extends self.ITextInstance {},
	MenuBGVid: class extends self.IWorldInstance {},
	MENUTITLE: class extends self.ITextInstance {},
	UIText: class extends self.ITextInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	DIATEXT: class extends self.ITextInstance {},
	DIATXTPERSN: class extends self.ITextInstance {},
	DIALOUGEBG: class extends self.IWorldInstance {},
	KEYTEXT: class extends self.ITextInstance {},
	PagerAsset2: class extends self.ISpriteInstance {},
	playerdiag: class extends self.ITextInstance {},
	Gameovertext: class extends self.ITextInstance {},
	TUTORIALTEXT: class extends self.ITextInstance {},
	tutdialouge: class extends self.IArrayInstance {},
	tutorialbox: class extends self.ISpriteInstance {},
	CamFollowerMenu: class extends self.ISpriteInstance {},
	CUTSCENECAM: class extends self.ISpriteInstance {},
	ItemList: class extends self.IArrayInstance {},
	C1: class extends self.IArrayInstance {},
	B1: class extends self.IArrayInstance {},
	Button: class extends self.IButtonInstance {},
	Button2: class extends self.IButtonInstance {},
	Collider2: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {}
}